name: "Setup Git Committer"
description: "Create app token and configure git user"
inputs:
  opencode-app-id:
    description: "OpenCode GitHub App ID"
    required: false
  opencode-app-secret:
    description: "OpenCode GitHub App private key"
    required: false
outputs:
  token:
    description: "GitHub token"
    value: ${{ steps.auth.outputs.token }}
  app-slug:
    description: "GitHub App slug"
    value: ${{ steps.auth.outputs.app-slug }}
runs:
  using: "composite"
  steps:
    - name: Create app token
      if: ${{ inputs.opencode-app-id != '' && inputs.opencode-app-secret != '' }}
      id: apptoken
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.opencode-app-id }}
        private-key: ${{ inputs.opencode-app-secret }}
        owner: ${{ github.repository_owner }}

    - name: Resolve auth token
      id: auth
      run: |
        token="${{ steps.apptoken.outputs.token }}"
        slug="${{ steps.apptoken.outputs.app-slug }}"
        if [ -z "$token" ]; then
          token="${{ github.token }}"
          slug="github-actions"
        fi
        echo "token=$token" >> "$GITHUB_OUTPUT"
        echo "app-slug=$slug" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Configure git user
      run: |
        slug="${{ steps.auth.outputs.app-slug }}"
        git config --global user.name "${slug}[bot]"
        git config --global user.email "${slug}[bot]@users.noreply.github.com"
      shell: bash

    - name: Clear checkout auth
      run: |
        git config --local --unset-all http.https://github.com/.extraheader || true
      shell: bash

    - name: Configure git remote
      run: |
        git remote set-url origin https://x-access-token:${{ steps.auth.outputs.token }}@github.com/${{ github.repository }}
      shell: bash
